# Generated by Django 5.2.17 on 2026-10-01 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "is_open",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to take this time off the market without deleting it.",
                    ),
                ),
            ],
            options={
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=70, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("math", "Math"),
                            ("science", "Science"),
                            ("english", "English & writing"),
                            ("cs", "Computer science"),
                            ("languages", "Languages"),
                            ("social", "Social studies"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                        max_length=12,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Officers: tick to make this conversation read-only.",
                    ),
                ),
                (
                    "student_read_through",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                (
                    "tutor_read_through",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="tutoring.availabilityslot",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutoring_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="tutoring.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-slot__start"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("uncomfortable", "Something made me uncomfortable"),
                            ("inappropriate", "Inappropriate message or behavior"),
                            ("no_show", "The other person did not show up"),
                            ("other", "Something else"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True, max_length=1000)),
                ("resolved", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="tutoring.booking",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["resolved", "-created"],
            },
        ),
        migrations.CreateModel(
            name="TutorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text='What students see. First name and last initial only, e.g. "Maya R."',
                        max_length=60,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        help_text='One line, e.g. "AP Calculus BC and Statistics"',
                        max_length=120,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=800)),
                (
                    "grade_label",
                    models.CharField(
                        blank=True, help_text='e.g. "Senior"', max_length=40
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="School library",
                        help_text="Where sessions happen",
                        max_length=100,
                    ),
                ),
                (
                    "is_listed",
                    models.BooleanField(
                        default=False,
                        help_text="Only officers should tick this, after approving the tutor.",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True, related_name="tutors", to="tutoring.subject"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.AddField(
            model_name="availabilityslot",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="tutoring.tutorprofile",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "removed",
                    models.BooleanField(
                        default=False,
                        help_text="Officers: hides the text from both people.",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tutoring.booking",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["booking", "id"], name="tutoring_me_booking_807786_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "confirmed")),
                fields=("slot",),
                name="one_confirmed_booking_per_slot",
            ),
        ),
        migrations.AddIndex(
            model_name="availabilityslot",
            index=models.Index(
                fields=["tutor", "start"], name="tutoring_av_tutor_i_f28bd4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("end__gt", models.F("start"))),
                name="slot_end_after_start",
            ),
        ),
    ]
